use std::env;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    generate_obfuscated_telemetry_secrets();
}

/// Read the telemetry endpoint + API key injected at build time (GitHub Secrets in
/// release CI) and emit them XOR-obfuscated with a per-build random key, so the
/// plaintext never appears in the shipped binary's strings.
///
/// This defeats `strings`/casual static scraping only — a determined reverse
/// engineer, or a MITM of the app's own HTTPS request, can still recover them. The
/// real protection is that the key is a write-only, rate-limited, rotatable ingest
/// token (see docs/telemetry.md), so a leaked key cannot do meaningful harm.
fn generate_obfuscated_telemetry_secrets() {
    // Rebuild when the injected values change (also fixes the option_env! caching
    // footgun where a changed env var would otherwise reuse a stale artifact).
    println!("cargo:rerun-if-env-changed=TELEMETRY_ENDPOINT");
    println!("cargo:rerun-if-env-changed=TELEMETRY_API_KEY");

    let endpoint = env::var("TELEMETRY_ENDPOINT").ok().filter(|s| !s.is_empty());
    let api_key = env::var("TELEMETRY_API_KEY").ok().filter(|s| !s.is_empty());

    let mut seed = build_seed();
    let mut code = String::from("// @generated by build.rs — obfuscated telemetry secrets. Do not edit.\n");
    code.push_str(&emit("TELEMETRY_ENDPOINT", endpoint.as_deref(), &mut seed));
    code.push_str(&emit("TELEMETRY_API_KEY", api_key.as_deref(), &mut seed));

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("telemetry_secrets.rs");
    fs::write(&dest, code).expect("failed to write telemetry_secrets.rs");
}

/// Per-build seed from wall-clock + pid — no external crates. A fresh key each build
/// means no fixed obfuscation constant sits in source or repeats across binaries.
fn build_seed() -> u64 {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x9E37_79B9_7F4A_7C15);
    let pid = std::process::id() as u64;
    (nanos ^ pid.wrapping_mul(0x9E37_79B9_7F4A_7C15)).max(1)
}

/// xorshift64 — one pseudo-random byte per call.
fn next_byte(seed: &mut u64) -> u8 {
    let mut x = *seed;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    *seed = x;
    (x & 0xff) as u8
}

/// Emit `<NAME>_SET`, `<NAME>_OBF`, `<NAME>_KEY` items for one secret.
fn emit(name: &str, value: Option<&str>, seed: &mut u64) -> String {
    match value {
        None => format!(
            "pub const {name}_SET: bool = false;\nstatic {name}_OBF: &[u8] = &[];\nstatic {name}_KEY: &[u8] = &[];\n"
        ),
        Some(v) => {
            let bytes = v.as_bytes();
            let key: Vec<u8> = (0..bytes.len()).map(|_| next_byte(seed)).collect();
            let obf: Vec<u8> = bytes.iter().zip(&key).map(|(b, k)| b ^ k).collect();
            format!(
                "pub const {name}_SET: bool = true;\nstatic {name}_OBF: &[u8] = &{obf:?};\nstatic {name}_KEY: &[u8] = &{key:?};\n"
            )
        }
    }
}
